半角スペースとハイフンを消す関数を追加
arsaga-partners/AndroidViewModelExtensions pull request #15
Opened 2020-12-24 08:51 UTC by Naoki-Hidaka

2020-12-24 09:50 UTC, Masaki-U requested changes

2020-12-24 09:50 UTC, Masaki-U commented on src/main/java/jp/co/arsaga/extensions/viewModel/MutableLivedata.kt
> +    this.value = value?.replace("\\s".toRegex(), "")
Stringにスペース消すメソッドがありましたよ。

2020-12-24 12:04 UTC, Naoki-Hidaka commented on src/main/java/jp/co/arsaga/extensions/viewModel/MutableLivedata.kt
> +    this.value = value?.replace("\\s".toRegex(), "")
trimのことですかね？
trimは先頭と末尾のスペースしか消してくれないみたいです
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/trim.html

2020-12-25 04:30 UTC, Masaki-U approved these changes
LGTM

2020-12-25 04:30 UTC, merged